### ISSUE TITLE
the solution of a280 is not valid.

### ISSUE THREAD

**Issue by changliang5811** [gaocrr/ELG#1]
Hello, when I try to run the TSPLib dataset with the code and model that you have provided, I find that the solution of a280 is not valid, I would like the author to check it, thanks!

Code for checking validity: 
`if done:
      assert (self.step_state.ninf_mask == float('-inf')).all(), 'ninf_mask is not all -inf, but done is True, so the solution is not valid.'`

Best regards!

**Comment by gaocrr** [comment]
Hello! Thanks for your interest in our work. I have checked the solutions of a280 and identified that out of the total of 2240 solutions (i.e., pomo_size * aug), 18 were found to be invalid. Fortunately, **the best solution that we report in the paper is valid** and this validity issue does not occur when solving other instances. 

I have located the bug in lines 72 and 290 of the "models.py" file. This bug is a numerical error that occurs due to division by zero. 
`sorted_dist = sorted_dist / sorted_dist.max(-1)[0].unsqueeze(-1)`
`dist_penalty = - sorted_dist / sorted_dist.max(-1)[0].unsqueeze(-1)`
The presence of 'NaN' values in the action probability results in the policy selecting random actions, which can potentially violate the constraints. Typically,  the max value in the distance matrix is a positive number. However, in the case of the a280 instance, there may be nodes that are too close together, causing the distance to become extremely small and resulting in a division by zero error. This bug can be easily resolved by adding a small positive number to the denominator  For example, 
`sorted_dist = sorted_dist / (sorted_dist.max(-1)[0].unsqueeze(-1) + 1e-6)`

We will fix this bug as soon as possible. Note that this bug does not occur on the best solution of a280. Therefore, the results we have reported do not require any updates. If you have any further concerns or questions, please let us know. Thank you for bringing this to our attention!
